# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SecondWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(494, 383)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SecondWindow.sizePolicy().hasHeightForWidth())
        SecondWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SecondWindow.setWindowIcon(icon)
        SecondWindow.setStyleSheet("background-color: rgb(44, 44, 44)")
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.textBaslik = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textBaslik.sizePolicy().hasHeightForWidth())
        self.textBaslik.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.textBaslik.setFont(font)
        self.textBaslik.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.textBaslik.setObjectName("textBaslik")
        self.verticalLayoutMain.addWidget(self.textBaslik)
        self.textIcerik = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.textIcerik.sizePolicy().hasHeightForWidth())
        self.textIcerik.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.textIcerik.setFont(font)
        self.textIcerik.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.textIcerik.setObjectName("textIcerik")
        self.verticalLayoutMain.addWidget(self.textIcerik)
        self.buttonKaydet = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        self.buttonKaydet.setFont(font)
        self.buttonKaydet.setStyleSheet("background-color: rgb(255, 195, 12)")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonKaydet.setIcon(icon1)
        self.buttonKaydet.setObjectName("buttonKaydet")
        self.verticalLayoutMain.addWidget(self.buttonKaydet)
        SecondWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "Add new note"))
        self.textBaslik.setPlaceholderText(_translate("SecondWindow", "Note Topic"))
        self.textIcerik.setPlaceholderText(_translate("SecondWindow", "Note Content"))
        self.buttonKaydet.setText(_translate("SecondWindow", "Save"))
